require("hassan.plugins-setup")
require("hassan.core.options")
require("hassan.core.keymaps")
require("hassan.core.colorscheme")
require("hassan.plugins.comment")
require("hassan.plugins.nvim-tree")
require("hassan.plugins.lualine")
require("hassan.plugins.telescope")
require("hassan.plugins.nvim-cmp")
require("hassan.plugins.lsp.mason")
require("hassan.plugins.lsp.lspsaga")
require("hassan.plugins.lsp.lspconfig")
--require("hassan.plugins.lsp.null-ls")
require("hassan.plugins.autopairs")
require("hassan.plugins.treesitter")
require("hassan.plugins.gitsigns")

